environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - npm --version
  - yarn test

build: off

cache:
  - "%LOCALAPPDATA%\\Yarn"
